### ISSUE TITLE
Textures not loading due to file names

### ISSUE THREAD

**Issue by ironHarrier** [Byte0Bard/BG3-Equipment-Generator#1]
I think I've discovered that textures files won't show up in the textures LSF file if there are any spaces in the texture's file name. That was a pain to figure out lol.

**Comment by Byte0Bard** [comment]
Thanks for letting me know! I’ll get on this.

**Comment by ironHarrier** [comment]
> Thanks for letting me know! I’ll get on this.

You're welcome! It had the side effect of making me keep my files better named and organized, so that bit is good lol
