### ISSUE TITLE
Body Type and Texture Issue

### ISSUE THREAD

**Issue by ironHarrier** [Byte0Bard/BG3-Equipment-Generator#2]
I get an error saying "Must select body type" when trying to select "Tiefling Fem." The Female Tiefling race UUID also doesn't appear in the root template. Also, my assets folder has both the DDS and source PNG texture files in it.

Otherwise, excellent update- I can't wait to see how this further evolves. Thank you for the file browser, it's perfect.

**Comment by Byte0Bard** [comment]
Thanks for letting me know. Turns out I spelled Tiefling wrong in my code for the Tiefling Fem. I’ll work out why the .pngs aren’t being removed.
