### ISSUE TITLE
[Question]  Updating armor without changing UUIDs?

### ISSUE THREAD

**Issue by robogena** [Byte0Bard/BG3-Equipment-Generator#3]
Hi Byte0Bard! I have a newbie question for you!

I'm running into an issue when I try to update armor. When I try to do something like add mesh support for strong bodies, the updated armor file has completely new UUIDS for the mod and everything internal (the meshes, the textures, the loca, etc). BG3 hates that so all the saves that used the old armor file no longer work.

What's the best way to update my armor but keep the same UUIDs? I read through the PDF tutorial but I wasn't completely clear on it. Is that what the presets are for? (Or profiles?) Or do I need to manually combine the updated file with the old one?

Thank you!!

**Comment by Byte0Bard** [comment]
Yeah the profiles make it so you don't have new UUIDs every time. They're save files to keep your information. To edit an item after loading it, double click its name in the table. To edit any materials or meshes, double click their names in their respective tables. Let me know if that helps!

**Comment by robogena** [comment]
Perfect!! That helps a lot! Thank you so much!
